'use strict'

module.exports.RESPONSE_MSG = {
  SUCCESS: 'SUCCESS',
  FAILED: 'FAILED',
  NOT_FOUND: 'ITEMS NOT FOUND',
  INVALID_INPUT: 'INVALID INPUT',
}

module.exports.RESPONSE_CODE = {
  SUCCESS: 0,
  FAILED: 1,
  NOT_FOUND: -1,
  INVALID_INPUT: 1

}
module.exports.HEALTHCHECKS = {
  FAILURE: 'FAILED',
  SUCCESS: 'OK'
}